---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd-deployment-xfusion
  name: httpd-deployment-xfusion
  namespace: httpd-namespace-xfusion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-deployment-xfusion
  template:
    metadata:
      labels:
        app: httpd-deployment-xfusion
    spec:
      containers:
      - image: httpd:latest
        name: httpd

---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service-xfusion
  namespace: httpd-namespace-xfusion
spec:
  selector:
    app: httpd-deployment-xfusion
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30004