apiVersion: apps/v1
kind: Deployment
metadata:
   name: httpd-frontend
   labels:
      app: myapp
spec:
  replicas: 3
  selector: 
    matchLabels: 
      name: httpd-frontend
  template: 
    metadata:
      name: httpd
      labels: 
        name: httpd-frontend
    spec:
      containers:
        - name: httpd
          image: httpd:2.4-alpine