apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: myapp-replicaset
   labels:
      app: myapp
spec:
  replicas: 3
  selector: 
    matchLabels: 
      env: myapp
  template: 
    metadata:
      name: nginx-1
      labels:
        env: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
         
      


